/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MusicManager;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author arthurkroth
 */
public class MusicManagerGUI extends javax.swing.JFrame {

    private MusicManager musicManager;
    
    /**
     * Creates new form MusicManager
     */
    public MusicManagerGUI() {
        initComponents();
        musicManager = new MusicManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMusicTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtArtistName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddLikedSong = new javax.swing.JButton();
        btnDeleteSong = new javax.swing.JButton();
        btnSearchSong = new javax.swing.JButton();
        btnDisplayLikedSongs = new javax.swing.JButton();
        btnMoveToGenre = new javax.swing.JButton();
        lblRepeat = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tglRepeat = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlaylist = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setText("Music Manager");

        jLabel2.setText("Music Title");

        jLabel3.setText("Artist Name");

        jLabel4.setText("Genre");

        jLabel5.setText("Playlist:");

        btnAddLikedSong.setText("Add to Liked Songs");
        btnAddLikedSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLikedSongActionPerformed(evt);
            }
        });

        btnDeleteSong.setText("Delete Song");

        btnSearchSong.setText("Search Song Title");

        btnDisplayLikedSongs.setText("List Liked Songs");
        btnDisplayLikedSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayLikedSongsActionPerformed(evt);
            }
        });

        btnMoveToGenre.setText("Move Last Liked to Genre Playlist");

        lblRepeat.setText("Repeat Off");

        jButton1.setText("List Rock Playlist");

        jButton2.setText("List Pop Paylist");

        tglRepeat.setText("Repeat Playlist");
        tglRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglRepeatActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listPlaylist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMusicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lblRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 7, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddLikedSong)
                            .addComponent(btnDeleteSong)
                            .addComponent(btnSearchSong)
                            .addComponent(btnDisplayLikedSongs)
                            .addComponent(btnMoveToGenre)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(tglRepeat))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMusicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(lblRepeat)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddLikedSong)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteSong)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchSong)
                        .addGap(25, 25, 25)
                        .addComponent(btnMoveToGenre)
                        .addGap(18, 18, 18)
                        .addComponent(tglRepeat)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisplayLikedSongs)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(64, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLikedSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLikedSongActionPerformed
        // TODO add your handling code here:
        String songName = txtMusicTitle.getText();
        String artistName = txtArtistName.getText();
        String genre = txtGenre.getText();
        
        //Creating a new song bject
        Song newSong = new Song(songName, artistName, genre);
        
        //Add to song to the playlist
        musicManager.likeSong(newSong);
        
        //wipping info from the text fields after adding song
        txtArtistName.setText("");
        txtMusicTitle.setText("");
        txtGenre.setText("");
    }//GEN-LAST:event_btnAddLikedSongActionPerformed

    private void tglRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglRepeatActionPerformed
        // TODO add your handling code here:
        if (tglRepeat.isSelected()) {
            lblRepeat.setText("Repeat ON");
        } else {
            lblRepeat.setText("Repeat OFF");
        }
    }//GEN-LAST:event_tglRepeatActionPerformed

    private void btnDisplayLikedSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayLikedSongsActionPerformed
        // TODO add your handling code here:
        List<String> songDetails = musicManager.getAllLikedSongDetails();
        
        DefaultListModel<String> model = new DefaultListModel<>();
        songDetails.forEach(model::addElement);
        
        listPlaylist.setModel(model);
        
//        txtDisplayPlaylist.setText(musicManager.listAllLikedSongs());
    }//GEN-LAST:event_btnDisplayLikedSongsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLikedSong;
    private javax.swing.JButton btnDeleteSong;
    private javax.swing.JButton btnDisplayLikedSongs;
    private javax.swing.JButton btnMoveToGenre;
    private javax.swing.JButton btnSearchSong;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRepeat;
    private javax.swing.JList<String> listPlaylist;
    private javax.swing.JToggleButton tglRepeat;
    private javax.swing.JTextField txtArtistName;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtMusicTitle;
    // End of variables declaration//GEN-END:variables
}
